INSERT INTO categories (name) VALUES ('History'), ('Movies'), ('Science'), ('Music'), ('Geography'),  ('Sports');

INSERT INTO questions (text, category_id, difficulty) VALUES
      ('Who was the first President of the United States?', 1, 1),
      ('In which year did World War II end?', 1, 1),


      ('Which movie features a young wizard attending Hogwarts School of Witchcraft and Wizardry?', 2, 1),
      ('Who voiced the character of Woody in the Toy Story films?', 2, 1),


      ('What is the chemical symbol for gold?', 3, 1),
      ('Which planet is closest to the Sun?', 3, 1),


      ('Which band performed the hit song "Yellow Submarine"?', 4, 1),
      ('Which instrument does a pianist play?', 4, 1),


      ('Which is the largest ocean on Earth?', 5, 1),
      ('What is the capital city of France?', 5, 1),


      ('In which sport would you perform a slam dunk?', 6, 1),
      ('How many players are on a standard soccer/football team on the field?', 6, 1);

INSERT INTO questions (text, category_id, difficulty) VALUES
-- History questions (category_id = 1)
('Which civilization built the Machu Picchu complex in Peru?', 1, 1),
('When was the Declaration of Independence signed?', 1, 1),
('Who was the first woman to fly solo across the Atlantic Ocean?', 1, 1),
('Which ancient wonder was located in Alexandria, Egypt?', 1, 1),
('Who painted the Mona Lisa?', 1, 1),

-- Movies questions (category_id = 2)
('What was the first feature-length animated film released by Disney?', 2, 1),
('Who directed the movie "Jaws"?', 2, 1),
('Which actor played Iron Man in the Marvel Cinematic Universe?', 2, 1),
('What film won the Academy Award for Best Picture in 2020?', 2, 1),
('In "The Lion King", what is the name of Simba''s father?', 2, 1),

-- Science questions (category_id = 3)
('Which gas do plants absorb from the atmosphere?', 3, 1),
('What is the hardest natural substance on Earth?', 3, 1),
('Which planet is known as the "Red Planet"?', 3, 1),
('What is the largest organ in the human body?', 3, 1),
('What is H2O commonly known as?', 3, 1),

-- Music questions (category_id = 4)
('Which singer is known as the "Queen of Pop"?', 4, 1),
('What instrument did Louis Armstrong play?', 4, 1),
('Which of these bands is from the UK?', 4, 1),
('What was Elvis Presley''s first #1 hit on the Billboard charts?', 4, 1),
('Which music genre originated in Jamaica?', 4, 1),

-- Geography questions (category_id = 5)
('Which country is home to the Great Barrier Reef?', 5, 1),
('What is the longest river in the world?', 5, 1),
('Which mountain range runs through Switzerland?', 5, 1),
('What is the capital of Canada?', 5, 1),
('Which of these countries is NOT in Europe?', 5, 1),

-- Sports questions (category_id = 6)
('In which sport would you use a shuttlecock?', 6, 1),
('How many points is a touchdown worth in American football?', 6, 1),
('Which country won the FIFA World Cup in 2018?', 6, 1),
('In which Olympic sport would you perform a vault?', 6, 1),
('What is the diameter of a basketball hoop in inches?', 6, 1);

INSERT INTO answers(question_id, text, is_correct) VALUES
    (2, '1943', false),
    (2, '1945', true),
    (2, '1947', false),
    (2, '1950', false),
    (3, 'The Chronicles of Narnia', false),
    (3, 'Harry Potter and the Sorcerer''s Stone', true),
    (3, 'Percy Jackson & the Olympians', false),
    (3, 'The Golden Compass', false),
    (4, 'Tim Allen', false),
    (4, 'Billy Crystal', false),
    (4, 'Tom Hanks', true),
    (4, 'John Goodman', false),
    (5, 'Go', false),
    (5, 'Gd', false),
    (5, 'Au', true),
    (5, 'Ag', false),
    (6, 'Earth', false),
    (6, 'Venus', false),
    (6, 'Mars', false),
    (6, 'Mercury', true),
    (7, 'The Rolling Stones', false),
    (7, 'The Beach Boys', false),
    (7, 'The Beatles', true),
    (7, 'The Monkees', false),
    (8, 'Drums', false),
    (8, 'Guitar', false),
    (8, 'Piano', true),
    (8, 'Violin', false),
    (9, 'Atlantic Ocean', false),
    (9, 'Indian Ocean', false),
    (9, 'Arctic Ocean', false),
    (9, 'Pacific Ocean', true),
    (10, 'Berlin', false),
    (10, 'London', false),
    (10, 'Paris', true),
    (10, 'Rome', false),
    (11, 'Football', false),
    (11, 'Basketball', true),
    (11, 'Hockey', false),
    (11, 'Soccer', false),
    (12, '9', false),
    (12, '10', false),
    (12, '11', true),
    (12, '12', false),
    (13, 'Maya', false),
    (13, 'Aztec', false),
    (13, 'Inca', true),
    (13, 'Olmec', false),
    (14, '1772', false),
    (14, '1776', true),
    (14, '1780', false),
    (14, '1789', false),
    (15, 'Bessie Coleman', false),
    (15, 'Harriet Quimby', false),
    (15, 'Amelia Earhart', true),
    (15, 'Amy Johnson', false),
    (16, 'The Hanging Gardens', false),
    (16, 'The Lighthouse (Pharos)', true),
    (16, 'The Colossus', false),
    (16, 'The Mausoleum', false),
    (17, 'Vincent van Gogh', false),
    (17, 'Michelangelo', false),
    (17, 'Leonardo da Vinci', true),
    (17, 'Pablo Picasso', false),
    (18, 'Fantasia', false),
    (18, 'Snow White and the Seven Dwarfs', true),
    (18, 'Bambi', false),
    (18, 'Pinocchio', false),
    (19, 'Francis Ford Coppola', false),
    (19, 'Martin Scorsese', false),
    (19, 'Steven Spielberg', true),
    (19, 'George Lucas', false),
    (20, 'Chris Evans', false),
    (20, 'Chris Hemsworth', false),
    (20, 'Mark Ruffalo', false),
    (20, 'Robert Downey Jr.', true),
    (21, '1917', false),
    (21, 'Joker', false),
    (21, 'Parasite', true),
    (21, 'Once Upon a Time in Hollywood', false),
    (22, 'Scar', false),
    (22, 'Mufasa', true),
    (22, 'Rafiki', false),
    (22, 'Zazu', false),
    (23, 'Oxygen', false),
    (23, 'Nitrogen', false),
    (23, 'Carbon Dioxide', true),
    (23, 'Hydrogen', false),
    (24, 'Titanium', false),
    (24, 'Diamond', true),
    (24, 'Platinum', false),
    (24, 'Quartz', false),
    (25, 'Jupiter', false),
    (25, 'Venus', false),
    (25, 'Mars', true),
    (25, 'Saturn', false),
    (26, 'Brain', false),
    (26, 'Liver', false),
    (26, 'Skin', true),
    (26, 'Heart', false),
    (27, 'Hydrogen Peroxide', false),
    (27, 'Oxygen', false),
    (27, 'Water', true),
    (27, 'Salt', false),
    (28, 'Beyoncé', false),
    (28, 'Lady Gaga', false),
    (28, 'Madonna', true),
    (28, 'Whitney Houston', false),
    (29, 'Saxophone', false),
    (29, 'Piano', false),
    (29, 'Trumpet', true),
    (29, 'Drums', false),
    (30, 'AC/DC', false),
    (30, 'The Rolling Stones', true),
    (30, 'Nirvana', false),
    (30, 'ABBA', false),
    (31, 'Blue Suede Shoes', false),
    (31, 'Heartbreak Hotel', true),
    (31, 'Hound Dog', false),
    (31, 'Jailhouse Rock', false),
    (32, 'Salsa', false),
    (32, 'Hip-hop', false),
    (32, 'Reggae', true),
    (32, 'Blues', false),
    (33, 'Brazil', false),
    (33, 'Thailand', false),
    (33, 'Australia', true),
    (33, 'Mexico', false),
    (34, 'Amazon', false),
    (34, 'Mississippi', false),
    (34, 'Yangtze', false),
    (34, 'Nile', true),
    (35, 'Andes', false),
    (35, 'Alps', true),
    (35, 'Rockies', false),
    (35, 'Himalayas', false),
    (36, 'Toronto', false),
    (36, 'Vancouver', false),
    (36, 'Ottawa', true),
    (36, 'Montreal', false),
    (37, 'Portugal', false),
    (37, 'Turkey', false),
    (37, 'Egypt', true),
    (37, 'Greece', false),
    (38, 'Table Tennis', false),
    (38, 'Badminton', true),
    (38, 'Tennis', false),
    (38, 'Squash', false),
    (39, '3', false),
    (39, '6', true),
    (39, '7', false),
    (39, '2', false),
    (40, 'Brazil', false),
    (40, 'Germany', false),
    (40, 'France', true),
    (40, 'Argentina', false),
    (41, 'Swimming', false),
    (41, 'Athletics', false),
    (41, 'Gymnastics', true),
    (41, 'Diving', false),
    (42, '16', false),
    (42, '18', true),
    (42, '20', false),
    (42, '22', false);